<a href="https://colab.research.google.com/github/marwan-2004-ds/task-1/blob/main/mlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris = load_iris()
X, y = iris.data, iris.target

X = StandardScaler().fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(  X, y, test_size=0.2, random_state=42, stratify=y )

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=50, batch_size=4, verbose=1)

val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
print("Loss:", val_loss)
print("Accuracy:", val_acc)

pred = model.predict(X_test, verbose=0)
print("Pred (first 5):", np.argmax(pred[:5], axis=1))
print("True  (first 5):", y_test[:5])

model.save('iris_tf.keras')
new_model = tf.keras.models.load_model('iris_tf.keras')


Epoch 1/50


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4179 - loss: 1.1436
Epoch 2/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6498 - loss: 1.0396
Epoch 3/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7336 - loss: 0.9449
Epoch 4/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6359 - loss: 0.9229
Epoch 5/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.7956
Epoch 6/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7081 - loss: 0.7321
Epoch 7/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6810 - loss: 0.6953
Epoch 8/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7519 - loss: 0.5946
Epoch 9/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6929 - loss: 0.6751
Epoch 10/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8465 - loss: 0.5249
Epoch 11/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8692 - loss: 0.5314
Epoch 12/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8591 - loss: 0.5226


In [ ]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

mlp = MLPRegressor(hidden_layer_sizes=(20, 10),  activation='relu', solver='adam', max_iter=5000, random_state=42)
mlp.fit(X_train_std, y_train)

y_pred_mlp = mlp.predict(X_test_std)
mse_mlp = mean_squared_error(y_test, y_pred_mlp)
r2_mlp = r2_score(y_test, y_pred_mlp)

print("=== MLPRegressor (20,10) ===")
print(f"MSE: {mse_mlp:.3f}")
print(f"R² : {r2_mlp:.3f}")

lr = LinearRegression()
lr.fit(X_train_std, y_train)
y_pred_lr = lr.predict(X_test_std)
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("\n=== Linear Regression (benchmark) ===")
print(f"MSE: {mse_lr:.3f}")
print(f"R² : {r2_lr:.3f}")

print("\nFirst 5 predictions (MLP vs LR) and true values:")
for i in range(5):
    print(f"MLP: {y_pred_mlp[i]:7.2f} | LR: {y_pred_lr[i]:7.2f} | True: {y_test[i]:7.2f}")


=== MLPRegressor (20,10) ===
MSE: 3217.266
R² : 0.393

=== Linear Regression (benchmark) ===
MSE: 2900.194
R² : 0.453

First 5 predictions (MLP vs LR) and true values:
MLP:   82.08 | LR:  139.55 | True:  219.00
MLP:  169.00 | LR:  179.52 | True:   70.00
MLP:  177.11 | LR:  134.04 | True:  202.00
MLP:  323.11 | LR:  291.42 | True:  230.00
MLP:   88.21 | LR:  123.79 | True:  111.00


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

wine = load_wine()
X, y = wine.data, wine.target
class_names = wine.target_names

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

mlp = MLPClassifier(
    hidden_layer_sizes=(64,),
    activation="relu",
    solver="adam",
    early_stopping=True,
    validation_fraction=0.15,
    n_iter_no_change=20,
    max_iter=5000,
    random_state=42
)

mlp.fit(X_train_std, y_train)

y_pred = mlp.predict(X_test_std)
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", acc)
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=class_names))


Accuracy: 0.9444444444444444

Confusion Matrix:
 [[12  0  0]
 [ 0 14  0]
 [ 0  2  8]]

Classification Report:
               precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        12
     class_1       0.88      1.00      0.93        14
     class_2       1.00      0.80      0.89        10

    accuracy                           0.94        36
   macro avg       0.96      0.93      0.94        36
weighted avg       0.95      0.94      0.94        36



In [ ]:
import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42
)

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

mlp_small = MLPClassifier(hidden_layer_sizes=(5,), max_iter=5000, random_state=42)
mlp_small.fit(X_train_std, y_train)

mlp_large = MLPClassifier(hidden_layer_sizes=(50,), max_iter=5000, random_state=42)
mlp_large.fit(X_train_std, y_train)

print("Small MLP - Train:", accuracy_score(y_train, mlp_small.predict(X_train_std)),
      "Test:", accuracy_score(y_test, mlp_small.predict(X_test_std)))
print("Large MLP - Train:", accuracy_score(y_train, mlp_large.predict(X_train_std)),
      "Test:", accuracy_score(y_test, mlp_large.predict(X_test_std)))


Small MLP - Train: 0.8653333333333333 Test: 0.936
Large MLP - Train: 0.9666666666666667 Test: 0.992


#the end
